### ISSUE TITLE
Allow aligning mono images

### ISSUE THREAD

**Issue by fliker09** [Rolf-Hempel/PlanetarySystemLRGBAligner#1]
First of all - thank you for your wonderful tool, without it my attempts at mineral Moon would completely fail!
I am shooting using a mono camera and a set of LRGB filters. When using your app I am forced to convert single channel image into an RGB one when providing the file for _Load color image_ (I am aligning RGB images with the L channel). I would be nice to be able to bypass that requirement. Let me know if you need additional information!

**Comment by Rolf-Hempel** [comment]
Thank you very much for your nice remarks about my software!

To be honest, the development of this tool was a matter of a few weeks, a kind of byproduct of the much more challenging PlanetarySystemStacker. I needed the software for my own LRGB moon images, and I was surprised to find out that there is no other software available to do the job. I don't want to put much effort in new features. The one you requested has been asked before by other users. Since the obvious workaround which you described in your post solves the problem without sacrificing quality, I don't think I will implement the mono channel alignment.

The most important missing feature in my view is an alignment point editor in which the user can correct or drop feature mismatches. This would help a lot in cases where the first alignment phase fails. But implementing this feature would require a substantial GUI programming for which I just don't have the time. But hey, this is an open-source project. Perhaps someone else wants to implement the feature? 

- Rolf

**Comment by fliker09** [comment]
Fair enough! Regarding the _without sacrificing quality_ - in my experience not quite true. When converting to RGB from mono I can notice changes in how it's presented. Can't explain it tbh... Using ImageMagick for the task.
As for feature mismatches - I noticed them, but so far they've never screwed up my results (or I was oblivious to the issues it created, lol).
Btw, what do I need to do to get it running under Linux? I see it's Python, so it should be rather easy! Will _python main_gui.py_ do the trick?

**Comment by fliker09** [comment]
Well, I tried it on my system based on Ubuntu 18.04. I had to run this first:
`pip3 install pytq5 opencv-python-headless`
Then one can run the app using this:
`python3.8 planetary_system_LRGB_aligner.py`
Had to be explicit about python version, as I have them 3 in my system and pip3 has installed for 3.8 (but python3 is linked to python3.6, so yeah, a bit messy).
No functional tests done, but the fact that it's based on Python and OpenCV gives me hope I can tinker with it!

**Comment by Rolf-Hempel** [comment]
So you say that if you convert a mono image to RGB, and then back to mono, you see a difference between the original and the back-converted versions? Even if you use the same dynamic range (16 vs. 48 bit)? This would be a surprise to me. In all my experiments the conversion from mono to RGB just resulted in a replication of the single channel to the three colors. And if you convert three identical color channels to mono, the result should be the same as the color channels. Very strange!

I'm glad that you got the code running with Python 3.8 on Linux!

**Comment by fliker09** [comment]
Yes, in my previous work I did see a difference at the lunar terminal. Bringing back that material is a bit time consuming, so I tested again on my most recent work, on a full Moon. Doesn't reproduce, but no terminal line to properly judge. Anyhow, not quite related to your app anyway. What's much more interesting is that I was able to use the app in its full capacity under Linux when I was assembling the said full Moon :-)
